# Generated by Django 5.0.7 on 2024-08-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('sports_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coaches/')),
            ],
        ),
    ]
