# Generated by Django 5.0.7 on 2024-08-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_is_active_coach_is_active_gym_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='blog_img/')),
            ],
        ),
    ]
